/*
 * STM32 (NUCLEO-F446RE) implementation of the platform interface.
 *
 * Contract in firmware/core/include/dronebench/platform.h. Pin map in plan
 * section 4.9; the analog front-end itself is the one built on day 11 and is
 * not touched by the port.
 */
#include "platform_stm32.h"

#include "dronebench/platform.h"
#include "stm32f4xx_hal.h"

/*
 * Generated by CubeMX. Declared here rather than pulled in from main.h so
 * that this file does not depend on which extra peripherals happen to be
 * enabled in the project on any given day.
 */
extern UART_HandleTypeDef huart2;
extern ADC_HandleTypeDef  hadc1;

/* LD2, the user LED on the NUCLEO. CubeMX defines these when the board
   selector is used; the fallback covers a project started from the bare MCU. */
#ifndef LD2_GPIO_Port
#define LD2_GPIO_Port GPIOA
#endif
#ifndef LD2_Pin
#define LD2_Pin GPIO_PIN_5
#endif

/*
 * Analog inputs. Arduino header names on the left because that is what is
 * printed on the board and therefore what the wires get plugged into.
 *
 *   A0 = PA0 = ADC1_IN0   battery divider node       (day 12)
 *   A1 = PA1 = ADC1_IN1   ACS724 OUT divider node    (day 13)
 *   A2 = PA4 = ADC1_IN4   ACS724 VCC divider node    (day 13, ratiometric zero)
 *
 * PA2/PA3 are USART2 to the ST-LINK and PA5 is LD2, so none of these collide
 * with anything the board already uses.
 */
#define ADC_CHANNEL_BATTERY    ADC_CHANNEL_0
#define ADC_CHANNEL_CURRENT    ADC_CHANNEL_1
#define ADC_CHANNEL_SENSOR_VCC ADC_CHANNEL_4

/*
 * Conversions averaged per reading, same reasoning as the ESP32 build: four
 * times the samples buys one bit, so 64 is worth three. Unlike the ESP32 the
 * result here is a raw count rather than an already-rounded millivolt, so
 * averaging before conversion loses nothing and is what happens.
 */
#define ADC_SAMPLES 64
/* Fewer for the reference: it is a slow-moving supply rail, not a signal. */
#define VREF_SAMPLES 16
#define ADC_FULL_SCALE 4095.0f
#define ADC_POLL_TIMEOUT_MS 10u

/*
 * 480 cycles, the longest the F4 offers. The dividers present about 4.9 kOhm
 * of Thevenin impedance and the sample-and-hold capacitor has to charge
 * through it; a short sampling time would report a number pulled toward
 * whatever the previous conversion left on the capacitor. The internal
 * reference separately requires at least 10 us, which this also satisfies.
 */
#define ADC_SAMPLING_TIME ADC_SAMPLETIME_480CYCLES

/*
 * ---------------------------------------------------------------------------
 * WHY VDDA IS MEASURED AND NOT ASSUMED
 * ---------------------------------------------------------------------------
 *
 * The ADC measures a ratio: raw / 4095 is the fraction of VDDA present at the
 * pin. Turning that into volts needs VDDA, and the obvious value to use is
 * 3300 mV because that is what the silkscreen says.
 *
 * It is not 3300 mV. On a NUCLEO the 3.3 V rail comes out of an LDO fed from
 * USB, and it sits wherever the board's own load leaves it — measured on this
 * one with a 1 mV meter: 3.359 V. Assuming nominal would put a 1.8 % error
 * into every voltage the bench ever reports, and calibration would not remove
 * it, because calibration is done against the same wrong assumption.
 *
 * So VDDA is derived instead. The chip carries a bandgap reference wired to
 * ADC channel 17, and the factory measured what that reference reads at
 * exactly 3.3 V and burned the number into system memory. Reading the same
 * reference now and comparing gives the supply:
 *
 *     VDDA = 3300 mV * VREFINT_CAL / VREFINT_measured
 *
 * A higher supply makes a fixed 1.21 V look like a smaller fraction of it, so
 * the measured count goes down as VDDA goes up — hence the ratio that way up.
 *
 * This is worth a cross-check on the bench, and the bench can do it: the
 * derived VDDA and the multimeter reading of the 3V3 pin are two independent
 * instruments looking at one rail, exactly like the two multimeters on day 11.
 * If they disagree by more than a few millivolts, one of them is wrong and the
 * project's habit is to find out which before trusting either.
 */
/*
 * Both of these come from ST's own stm32f4xx_ll_adc.h, pulled in by the HAL:
 * VREFINT_CAL_ADDR is 0x1FFF7A2A and VREFINT_CAL_VREF is 3300 mV. Restating
 * them here would be a second copy of a number that must agree with the
 * silicon -- and the copy is the one that would go stale.
 */
#define VREFINT_CAL_VDDA_MV ((float)VREFINT_CAL_VREF)

/*
 * The factory value should land near 1.21 V of a 3.3 V full scale, i.e.
 * 1.21 / 3.3 * 4095 = 1502 counts, and the datasheet spread on VREFINT is
 * 1.18-1.24 V, so 1465-1539. The window below is wider than that on purpose:
 * it is not checking the part against its datasheet, it is checking that this
 * address holds a calibration at all rather than erased flash (0xFFFF), a
 * lock byte, or something belonging to a different part number.
 */
#define VREFINT_CAL_MIN 1300u
#define VREFINT_CAL_MAX 1700u

/* An LDO that has left this window is not a supply worth measuring against. */
#define VDDA_PLAUSIBLE_MIN_MV 2800.0f
#define VDDA_PLAUSIBLE_MAX_MV 3600.0f

static float s_vdda_mv; /* 0 until established; 0 means every read refuses */

/*
 * Simulation state. Default on, same as the ESP32 build: until a divider is
 * wired to this particular board and calibrated, the real path has nothing
 * honest to say.
 */
static struct {
    bool        enabled;
    simulator_t sim;
} s_source = {
    .enabled = true,
};

/* ------------------------------------------------------------------------ */
/* Time                                                                     */
/* ------------------------------------------------------------------------ */

/*
 * The core requires this never to go backwards, and requires microseconds.
 * HAL_GetTick() gives milliseconds, which is 500 times too coarse for a
 * sampler running at 500 Hz — every sample in a period would carry the same
 * timestamp and every interval between them would be zero.
 *
 * The missing resolution is already in the machine: SysTick counts down from
 * LOAD to 0 once per millisecond, so its current value is the fraction of the
 * millisecond that has not elapsed yet.
 *
 * Reading the two separately is the trap. Between reading the tick and
 * reading the counter, the counter can wrap and the tick advance, and the
 * result is a timestamp built from the old millisecond and the new fraction —
 * a jump backwards of almost a full millisecond, on an interface whose one
 * hard requirement is that it never jumps backwards. Reading the tick on both
 * sides and retrying when it moved closes that window.
 *
 * Not reentrant: the static state below would be corrupted by a call from an
 * interrupt that preempted another call. The superloop this port starts with
 * has no such call. When day 10's task structure arrives here, this needs a
 * critical section.
 */
uint64_t platform_time_us(void)
{
    static uint64_t s_last_us;  /* monotonic guard */
    static uint32_t s_prev_ms;
    static uint64_t s_ms_epoch; /* HAL_GetTick() wraps after ~49.7 days */

    uint32_t ms_before;
    uint32_t ms_after;
    uint32_t counter;
    uint32_t reload;
    uint64_t sub_us;
    uint64_t now_us;

    do {
        ms_before = HAL_GetTick();
        counter   = SysTick->VAL;
        ms_after  = HAL_GetTick();
    } while (ms_before != ms_after);

    reload = SysTick->LOAD + 1u; /* ticks per millisecond */
    if (reload == 0u) {
        /* SysTick is not running. Millisecond resolution is all there is. */
        sub_us = 0u;
    } else {
        /* Counts down, so elapsed is the distance from the top. */
        sub_us = ((uint64_t)(reload - counter) * 1000u) / reload;
    }

    if (ms_before < s_prev_ms) {
        s_ms_epoch += 0x100000000ULL;
    }
    s_prev_ms = ms_before;

    now_us = (s_ms_epoch + ms_before) * 1000ULL + sub_us;

    /* Belt and braces. Anything that gets past the retry loop above still
       must not be allowed to reach the core as a backwards step, because
       every duration in the core is an unsigned subtraction and a backwards
       step becomes an enormous positive interval. */
    if (now_us < s_last_us) {
        now_us = s_last_us;
    }
    s_last_us = now_us;

    return now_us;
}

/* ------------------------------------------------------------------------ */
/* ADC                                                                      */
/* ------------------------------------------------------------------------ */

static bool adc_read_raw(uint32_t channel, uint32_t *raw)
{
    ADC_ChannelConfTypeDef cfg = {0};

    cfg.Channel      = channel;
    cfg.Rank         = 1;
    cfg.SamplingTime = ADC_SAMPLING_TIME;

    if (HAL_ADC_ConfigChannel(&hadc1, &cfg) != HAL_OK) {
        return false;
    }
    if (HAL_ADC_Start(&hadc1) != HAL_OK) {
        return false;
    }
    if (HAL_ADC_PollForConversion(&hadc1, ADC_POLL_TIMEOUT_MS) != HAL_OK) {
        HAL_ADC_Stop(&hadc1);
        return false;
    }

    *raw = HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);
    return true;
}

static bool adc_read_average(uint32_t channel, uint32_t samples, float *mean)
{
    uint32_t sum = 0;
    uint32_t i;

    for (i = 0; i < samples; i++) {
        uint32_t raw;

        /* Not an assert and not a retry: a driver hiccup must not reboot a
           bench with a motor spinning, and must not be averaged over either.
           sampler_t counts a refused reading as sensor_failures, which is
           where a fault belongs. */
        if (!adc_read_raw(channel, &raw)) {
            return false;
        }
        sum += raw;
    }

    /* 64 * 4095 is 262 080 — exact in a float's 24-bit mantissa with room to
       spare, so nothing is lost in the accumulation. */
    *mean = (float)sum / (float)samples;
    return true;
}

static bool measure_vdda_mv(float *vdda_mv)
{
    uint16_t cal = *VREFINT_CAL_ADDR;
    float    measured;
    float    result;

    if (cal < VREFINT_CAL_MIN || cal > VREFINT_CAL_MAX) {
        return false;
    }
    if (!adc_read_average(ADC_CHANNEL_VREFINT, VREF_SAMPLES, &measured)) {
        return false;
    }
    if (measured < 1.0f) {
        return false;
    }

    result = VREFINT_CAL_VDDA_MV * (float)cal / measured;
    if (result < VDDA_PLAUSIBLE_MIN_MV || result > VDDA_PLAUSIBLE_MAX_MV) {
        return false;
    }

    *vdda_mv = result;
    return true;
}

float platform_stm32_vdda_mv(void) { return s_vdda_mv; }

/*
 * Millivolts at the battery divider's node, before any calibration of ours.
 *
 * One half of every calibration pair; the other half is what the multimeter
 * says about the same point at the same moment. Contract in platform.h,
 * arithmetic in core/measurements/calibration.c.
 *
 * The supply is re-measured on every call rather than cached from init. VDDA
 * moves with the board's own load — the LED, the ST-LINK, whatever the ADC
 * itself is doing — and a reference measured under one load applied to a
 * signal measured under another puts the difference straight into the result.
 * Pairing them in the same burst removes it. Sixteen extra conversions is a
 * few hundred microseconds, which buys more than it costs.
 */
bool platform_adc_read_millivolts(float *value)
{
    float vdda_mv;
    float counts;

    if (!measure_vdda_mv(&vdda_mv)) {
        s_vdda_mv = 0.0f;
        return false;
    }
    s_vdda_mv = vdda_mv;

    if (!adc_read_average(ADC_CHANNEL_BATTERY, ADC_SAMPLES, &counts)) {
        return false;
    }

    *value = counts * vdda_mv / ADC_FULL_SCALE;
    return true;
}

/*
 * Both channels come from one simulator call so they stay consistent with
 * each other; sampling them separately would let the timeline advance between
 * the two, and voltage would describe a slightly different instant than the
 * current it is paired with.
 */
static void simulated_pair(float *voltage_v, float *current_a)
{
    simulator_read(&s_source.sim, platform_time_us(), voltage_v, current_a);
}

bool platform_adc_read_voltage(float *value)
{
    if (s_source.enabled) {
        float current;

        simulated_pair(value, &current);
        return true;
    }

    /* Day 12 on this board. Becomes: read millivolts, then
       calibration_apply(&s_voltage_cal, mv, value). It stays false until a fit
       exists and is stored — an uncalibrated reading is not a rough
       measurement of the battery, it is a measurement of something else. */
    return false;
}

bool platform_adc_read_current(float *value)
{
    if (s_source.enabled) {
        float voltage;

        simulated_pair(&voltage, value);
        return true;
    }

    /* Day 13. */
    return false;
}

bool platform_ref_read_current(float *value)
{
    /* Day 14, and only if the INA226 is actually fitted. */
    (void)value;
    return false;
}

/* ------------------------------------------------------------------------ */
/* Console, watchdog, LED                                                   */
/* ------------------------------------------------------------------------ */

/*
 * USART2 is wired to the ST-LINK's virtual COM port on the NUCLEO, so this
 * comes out of the same USB cable that flashes the board and `make log`
 * connects to it with no change but the device name.
 *
 * Takes a length rather than a NUL-terminated string on purpose: the binary
 * protocol in day 7 sends frames containing zero bytes.
 */
void platform_uart_write(const char *data, size_t size)
{
    /* HAL takes a uint16_t length. Nothing here sends 64 kB in one call, but a
       silent truncation is a worse way to find that out than a second call. */
    while (size > 0u) {
        uint16_t chunk = (size > 0xFFFFu) ? 0xFFFFu : (uint16_t)size;

        (void)HAL_UART_Transmit(&huart2, (const uint8_t *)data, chunk,
                                HAL_MAX_DELAY);
        data += chunk;
        size -= chunk;
    }
}

void platform_watchdog_feed(void)
{
    /*
     * The independent watchdog is not enabled in the initial CubeMX project,
     * and a call that silently does nothing is exactly the failure the ESP32
     * build spent day 10 discovering. So this is a compile-time switch: turn
     * IWDG on in CubeMX, define PLATFORM_STM32_USE_IWDG, and the call starts
     * doing something. Until then it visibly does not.
     */
#ifdef PLATFORM_STM32_USE_IWDG
    extern IWDG_HandleTypeDef hiwdg;
    (void)HAL_IWDG_Refresh(&hiwdg);
#endif
}

void platform_status_led_set(bool on)
{
    HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/* ------------------------------------------------------------------------ */
/* Init                                                                     */
/* ------------------------------------------------------------------------ */

/*
 * The status LED belongs to the platform, not to whoever happens to blink it
 * first.
 *
 * CubeMX leaves PA5 unconfigured here: with the board selector it delegates
 * the LED to the BSP, which runs after the USER CODE block this init is called
 * from. Depending on that ordering would make the LED work or not depending on
 * where a call sits in a generated file -- so the pin is configured here, the
 * same way the ESP32 build configures its own.
 */
static void led_gpio_init(void)
{
    GPIO_InitTypeDef cfg = {0};

    /* GPIOA specifically, because LD2_GPIO_Port is GPIOA on this board and on
       the fallback above. A different port would need a different clock. */
    __HAL_RCC_GPIOA_CLK_ENABLE();

    cfg.Pin   = LD2_Pin;
    cfg.Mode  = GPIO_MODE_OUTPUT_PP;
    cfg.Pull  = GPIO_NOPULL;
    cfg.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LD2_GPIO_Port, &cfg);
}

void platform_stm32_init(void)
{
    float vdda_mv;

    led_gpio_init();
    platform_status_led_set(false);

    /* Establishing the supply is the first real thing the ADC does, and it is
       allowed to fail: an unknown reference is reported as unknown rather
       than replaced with a nominal value that looks just as plausible. */
    s_vdda_mv = measure_vdda_mv(&vdda_mv) ? vdda_mv : 0.0f;
}

void platform_stm32_set_simulation(bool enabled, sim_profile_t profile)
{
    s_source.enabled = enabled;
    simulator_init(&s_source.sim, profile);
}

bool platform_stm32_simulation_enabled(void) { return s_source.enabled; }

sim_profile_t platform_stm32_simulation_profile(void)
{
    return s_source.sim.profile;
}
